approve_by_comment: true
approve_regex: ^(Approv|LGTM|:thumbsup:)
author_approval: ignored
reject_regex: ^(Reject|:-1:|:thumbsdown:)
reset_on_push: true
reviewers:
  members:
  - remmelt
  name: default
  required: 1
