approve_by_comment: true
approve_regex: '^(Approv|LGTM)'
author_approval: ignored
reject_regex: '^(Reject)'
reset_on_push: true
reviewers:
  -
    name: remmelts
    required: 1
    members:
      - remmelt
